require File.join(File.dirname(__FILE__),'../lib/rake_helper')

define_source_tasks  "human_ppi" => "http://www.genomeknowledge.org/download/current/homo_sapiens.interactions.txt.gz",
  "protein_pathway" => "http://www.genomeknowledge.org/download/current/uniprot_2_pathways.stid.txt",
  "pathway_genesets" => "http://www.genomeknowledge.org/download/current/ReactomePathways.gmt.zip"

process_tsv :protein_protein, 'human_ppi',
  :key         => 0, 
  :fix         => lambda{|l| l.gsub(/\t[a-z ]+:/i,"\t").gsub(/^[a-z ]+:/i,'')}, 
  :fields      => [3,6,7,8], 
  :header_hash => "#",
  :merge       => true,
  :keep_empty  => true do 

  headers ['UniProt/SwissProt Accession', 'Interactor UniProt/SwissProt Accession', 'Interaction Type', 'Reactions Involved', 'Interaction PMIDS']
end

process_tsv :protein_pathway, 'protein_pathway',
  :key         => 0, 
  :fix         => lambda{|l| l.gsub(/\t[a-z ]+:/i,"\t").gsub(/^[a-z ]+:/i,'')}, 
  :fields      => [1,2], 
  :header_hash => "#",
  :merge       => true,
  :keep_empty  => true do 

  headers ['UniProt/SwissProt Accession', 'Pathway ID', 'Pathway Description']
end

process_tsv :pathway_genesets, 'pathway_genesets',
  :key         => 0, 
  :fix         => lambda{|l| parts = l.split("\t"); [parts[0], parts[2..-1] * "|"] * "\t"}, 
  :keep_empty  => true do 

  headers ['Reactome Pathway Name', 'Associated Gene Name']
end

