require File.join(File.dirname(__FILE__),'../lib/rake_helper')

define_source_tasks "matador" => "http://matador.embl.de/media/download/matador.tsv.gz"

process_tsv :protein_drug, 'matador',
  :key_field  => 3, 
  :fix     => lambda{|l| l.sub(/9606./,'')}, 
  :fields   => [1,0,7,8,9,10,11,12], 
  :header_hash => "",
  :keep_empty => true do 

  headers ['Ensembl Protein ID', 'Chemical', 'Matador ID', 'Score', 'Annotation', 'Mesh_Score', 'Mesh_Annotation', 'Matador_Score', 'Matador_Annotation']
end

