require File.join(File.dirname(__FILE__),'../lib/rake_helper')

define_source_tasks "protein_chemicals" => "http://stitch.embl.de:8080/download/protein_chemical.links.v2.0.tsv.gz",
  "chemicals" => "http://stitch.embl.de:8080/download/chemical.aliases.v2.0.tsv.gz"

process_tsv :protein_chemical, 'protein_chemicals',
  :key => 1,
  :grep => "9606\.", 
  :fix => lambda{|l| l.sub(/9606\./,'')},
  :keep_empty => true do

  headers ['Ensembl Protein ID', 'STITCH Chemical ID', 'Score']
end

$grep_re = []
process_tsv :chemicals, 'chemicals',
  :grep => $grep_re, 
  :key  => 0 do

  Rake::Task['protein_chemical'].invoke

  Log.debug "Getting chemicals"
  chemicals = TSV.new('protein_chemical', :key => 1, :fields => []).keys
  Log.debug "Getting chemicals [done]"

  $grep_re.replace chemicals

  headers ['STITCH Chemical ID', 'Name', 'Source']
end

