#!/bin/bash

INSTALL_HELPER_FILE="$1"
RBBT_SOFTWARE_DIR="$2"

source "$INSTALL_HELPER_FILE"

name='OncodriveFM'
url="http://bg.upf.edu/group/projects/oncodrivefm-1.1.0.tar.gz"


install_src "$name" "$url"

