require File.join(File.dirname(__FILE__),'../lib/rake_helper')


file :protein_protein do |t|
  begin
    tsv = PhGx.share.hprd["BINARY_PROTEIN_PROTEIN_INTERACTIONS.txt"].tsv :merge => true
  rescue
    raise "File BINARY_PROTEIN_PROTEIN_INTERACTIONS.txt not found in 'share/hprd', download manually from http://www.hprd.org/"
  end
  tsv.key_field = "Associated Gene Name 1"
  tsv.fields = ["HPRD id 1","RefSeq Protein ID 1","Associated Gene Name 2","HPRD id 2","RefSeq Protein ID 2", "Experiment type", "PMID"]
  tsv.namespace = "Hsa"

  Open.write(t.name, tsv.to_s)
end
